### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by jeffwheeler**
Hi Mahesh,

In my previous pull request (sorry, it was still WIP, not actually intended to be merged 😄), I had commented out some code that caused crashes for me. As far as I can tell, the various `QPainter` objects in the various `widget()` calls don't actually do anything, and this commit removes the code I had commented out. From what I can tell, the `QFrame` objects that this commit removes were never added to the window, so they don't seem to have any impact at all.

This file seems to have been generated by some tool. (I guess that because the various `QFrame` objects have names like `frame14`, `frame20`, `frame21`, etc..) Is that true? If so, what tool?

### CODE REVIEW

**Comment by gseim** [comment]
Qpainter has been used to draw borders around some of the pop-up boxes (just beautification, it does affect the functionality). These can be commented out.
The code was originally written by one of our grad students, Ruchita. I talked to her and confirmed that the variable names such as frame14, frame20 were her own. She did not use any tools to generate the code.

Please also look at this:
I am facing an issue after the changes were made.
The GRC GUI and the GSEIM numerical engine work
well, but the plotting gui, when tried on ubuntu,
is giving the following error:

QT6
Traceback (most recent call last):
  File "/home/mbp2/gseim_grc/gseim/exec/gseim_plot.py", line 4781, in
<module>
    class PlotWindow(QMainWindow, PlotCanvas):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
------------

Would greatly appreciate your suggestions.

Mahesh

**Comment by gseim** [comment]
Sorry about the bold face, was not intended.
Mahesh

**Comment by jeffwheeler** [comment]
Hi Mahesh,

Can you try out the latest revision of this pull request? I added commit [3b9c82e](https://github.com/gseim/gseim/pull/6/commits/3b9c82e9626d00fabed1375ae5eb523645b27580) to remove the multi-inheritance from `PlotWindow`. Actually, I'm a little surprised if the error you see came from my commit, because I didn't change that part, but I'm a bit confused by what was there too. I think using multi-inheritance there is confusing, so I've changed it instead to make a `PlotCanvas` a child element of `PlotWindow`, which makes more sense to me.

Jeff

**Comment by gseim** [comment]
tried it, getting this error now:

QWidget: Must construct a QApplication before a QWidget
Aborted (core dumped)

**Comment by jeffwheeler** [comment]
I guess this is an issue with two versions of PyQT (5 and 6) both being imported. I've changed the Matplotlib QT backend to remove the PyQT5 reference, in alignment with [the latest documentation](https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_qt_sgskip.html), so that _might_ help, although I wasn't able to reproduce your issue so I'm not certain.

Can you run `pip3 list` to share the package versions? I use a virtual environment, so these are the dependencies that GSEIM requires:
```
(gseim_venv) gseim_grc ᐅ pip3 list
Package             Version
------------------- -------
cycler              0.11.0
fonttools           4.34.4
gseim               0.0.1
importlib-resources 5.8.0
kiwisolver          1.4.3
matplotlib          3.5.2
numpy               1.23.1
packaging           21.3
Pillow              9.2.0
pip                 22.1.2
psutil              5.9.1
pycairo             1.21.0
PyGObject           3.42.1
pyparsing           3.0.9
PyQt6               6.3.1
PyQt6-Qt6           6.3.1
PyQt6-sip           13.4.0
python-dateutil     2.8.2
PyYAML              6.0
setuptools          60.10.0
six                 1.16.0
zipp                3.8.1
```

Separately, I'd like to propose packaging the Python code into modules so that dependency (including versions) can be specified. I'll make a separate discussion for that topic.

**Comment by jeffwheeler** [comment]
Mahesh,

Moving back to the Github thread, I have pushed a new commit [b0f1ad2](https://github.com/gseim/gseim/pull/6/commits/b0f1ad2a07a33053326d69c2acf5ecbba60dd756) that should dynamically import the best version of PyQt depending on what the user has installed. I've tested it in the compatibility matrix shown below.

| Matplotlib version  | PyQt version | Resulting PyQt API version |
| ------------- | ------------- | ------------- |
| 3.1.2. | PyQt5 | PyQt5 |
| 3.1.2  | PyQt6 | Not supported (`ImportError: Failed to import any qt binding`). This is expected because this version of Matplotlib does not support PyQt6. | 
| 3.1.2  | PyQt5 _and_ PyQt6  | PyQt5 |
| 3.5.2 |  PyQt5 | PyQt5 |
| 3.5.2 | PyQt6 | PyQt6 |
| 3.5.2 | PyQt5 _and_ PyQt6 | PyQt6 |

**Comment by gseim** [comment]
gseim_plot.py opens the GUI for me, also plots fine in single-plot mode.

When multi-plot is selected, it is giving this error:

AttributeError: 'PlotWindow' object has no attribute 'ax_multi'

To reproduce the error, please run the project dc_to_dc/buck.in, click on the plot icon, select buck.in, select IL and V_out as the y variables and click on multi-plot.

Mahesh

**Comment by jeffwheeler** [comment]
Should be fixed now.

**Comment by gseim** [comment]
works. Thanks.

**Comment by jeffwheeler** [comment]
Closing this, since you've integrated this into your last commit. Thanks!

**Pull request closed without merging**
